### ISSUE TITLE
Installation Failure

### ISSUE THREAD

**Issue by pablomat** [FarmBot/farmbot-web-frontend#173]
When populating the postgres db i get the following error. The DB is created but the rake command aborts. 
```
$ rake db:create:all db:migrate db:seed --trace

rake aborted!
ActiveModel::UnknownAttributeError: unknown attribute 'planted_at' for Plant.
/home/emilio/.rvm/gems/ruby-2.3.3@farmbot-web-app/gems/activemodel-5.0.0.1/lib/active_model/attribute_assignment.rb:48:in `_assign_attribute'
/home/emilio/.rvm/gems/ruby-2.3.3@farmbot-web-app/gems/activemodel-5.0.0.1/lib/active_model/attribute_assignment.rb:40:in `block in _assign_attributes'
/home/emilio/.rvm/gems/ruby-2.3.3@farmbot-web-app/gems/activemodel-5.0.0.1/lib/active_model/attribute_assignment.rb:39:in `each'
/home/emilio/.rvm/gems/ruby-2.3.3@farmbot-web-app/gems/activemodel-5.0.0.1/lib/active_model/attribute_assignment.rb:39:in `_assign_attributes'
/home/emilio/.rvm/gems/ruby-2.3.3@farmbot-web-app/gems/activerecord-5.0.0.1/lib/active_record/attribute_assignment.rb:26:in `_assign_attributes'
/home/emilio/.rvm/gems/ruby-2.3.3@farmbot-web-app/gems/activemodel-5.0.0.1/lib/active_model/attribute_assignment.rb:33:in `assign_attributes'
/home/emilio/.rvm/gems/ruby-2.3.3@farmbot-web-app/gems/activerecord-5.0.0.1/lib/active_record/core.rb:319:in `initialize'
/home/emilio/.rvm/gems/ruby-2.3.3@farmbot-web-app/gems/activerecord-5.0.0.1/lib/active_record/inheritance.rb:65:in `new'
/home/emilio/.rvm/gems/ruby-2.3.3@farmbot-web-app/gems/activerecord-5.0.0.1/lib/active_record/inheritance.rb:65:in `new'
/home/emilio/.rvm/gems/ruby-2.3.3@farmbot-web-app/gems/activerecord-5.0.0.1/lib/active_record/persistence.rb:33:in `create'
/home/emilio/farmbot-web-app/db/seeds.rb:18:in `block in <top (required)>'
/home/emilio/farmbot-web-app/db/seeds.rb:17:in `times'
/home/emilio/farmbot-web-app/db/seeds.rb:17:in `<top (required)>'
/home/emilio/.rvm/gems/ruby-2.3.3@farmbot-web-app/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `load'
/home/emilio/.rvm/gems/ruby-2.3.3@farmbot-web-app/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `block in load'
/home/emilio/.rvm/gems/ruby-2.3.3@farmbot-web-app/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
/home/emilio/.rvm/gems/ruby-2.3.3@farmbot-web-app/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `load'
/home/emilio/.rvm/gems/ruby-2.3.3@farmbot-web-app/gems/railties-5.0.0.1/lib/rails/engine.rb:549:in `load_seed'
/home/emilio/.rvm/gems/ruby-2.3.3@farmbot-web-app/gems/activerecord-5.0.0.1/lib/active_record/tasks/database_tasks.rb:268:in `load_seed'
/home/emilio/.rvm/gems/ruby-2.3.3@farmbot-web-app/gems/activerecord-5.0.0.1/lib/active_record/railties/databases.rake:196:in `block (2 levels) in <top (required)>'
/home/emilio/.rvm/gems/ruby-2.3.3@farmbot-web-app/gems/rake-11.3.0/lib/rake/task.rb:248:in `block in execute'
/home/emilio/.rvm/gems/ruby-2.3.3@farmbot-web-app/gems/rake-11.3.0/lib/rake/task.rb:243:in `each'
/home/emilio/.rvm/gems/ruby-2.3.3@farmbot-web-app/gems/rake-11.3.0/lib/rake/task.rb:243:in `execute'
/home/emilio/.rvm/gems/ruby-2.3.3@farmbot-web-app/gems/rake-11.3.0/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
/home/emilio/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/home/emilio/.rvm/gems/ruby-2.3.3@farmbot-web-app/gems/rake-11.3.0/lib/rake/task.rb:180:in `invoke_with_call_chain'
/home/emilio/.rvm/gems/ruby-2.3.3@farmbot-web-app/gems/rake-11.3.0/lib/rake/task.rb:173:in `invoke'
/home/emilio/.rvm/gems/ruby-2.3.3@farmbot-web-app/gems/rake-11.3.0/lib/rake/application.rb:152:in `invoke_task'
/home/emilio/.rvm/gems/ruby-2.3.3@farmbot-web-app/gems/rake-11.3.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/home/emilio/.rvm/gems/ruby-2.3.3@farmbot-web-app/gems/rake-11.3.0/lib/rake/application.rb:108:in `each'
/home/emilio/.rvm/gems/ruby-2.3.3@farmbot-web-app/gems/rake-11.3.0/lib/rake/application.rb:108:in `block in top_level'
/home/emilio/.rvm/gems/ruby-2.3.3@farmbot-web-app/gems/rake-11.3.0/lib/rake/application.rb:117:in `run_with_threads'
/home/emilio/.rvm/gems/ruby-2.3.3@farmbot-web-app/gems/rake-11.3.0/lib/rake/application.rb:102:in `top_level'
/home/emilio/.rvm/gems/ruby-2.3.3@farmbot-web-app/gems/rake-11.3.0/lib/rake/application.rb:80:in `block in run'
/home/emilio/.rvm/gems/ruby-2.3.3@farmbot-web-app/gems/rake-11.3.0/lib/rake/application.rb:178:in `standard_exception_handling'
/home/emilio/.rvm/gems/ruby-2.3.3@farmbot-web-app/gems/rake-11.3.0/lib/rake/application.rb:77:in `run'
/home/emilio/.rvm/gems/ruby-2.3.3@farmbot-web-app/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/home/emilio/.rvm/gems/ruby-2.3.3@farmbot-web-app/bin/rake:22:in `load'
/home/emilio/.rvm/gems/ruby-2.3.3@farmbot-web-app/bin/rake:22:in `<main>'
/home/emilio/.rvm/gems/ruby-2.3.3@farmbot-web-app/bin/ruby_executable_hooks:15:in `eval'
/home/emilio/.rvm/gems/ruby-2.3.3@farmbot-web-app/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:seed
```

# Actual Behavior

# Steps to Reproduce

**Comment by RickCarlino** [comment]
@pablomat Try pulling the latest master and try again. We just made some changes to the `Plant` model recently. I can re-open if that doesn't fix it. Closing for now.

**Comment by RickCarlino** [comment]
Actually- please move the conversation to the [Web API](https://github.com/FarmBot/Farmbot-Web-API) repository, as database issues are not part of the frontend.
